### ISSUE TITLE
Тест #63: восстановление потоков входа, выхода и управления при обратном преобразовании из UML в IDEF0

### ISSUE THREAD

**Issue by FXKK44** [stankin/oop-model#15]
При преобразовании диаграмм IDEF0 в диаграммы прецедентов UML теряется информация обо всех информационных и материальных потоках - о входах, выходах и управлении. При обратном преобразовании все эти потоки должны быть восстановлены или спроектированы заново.

**Comment by egoistos** [comment]
#63
