### ISSUE TITLE
SWOT: Моделирование BPMN

### ISSUE THREAD

**Issue by ndkator** [stankin/oop-model#26]
- BPMN-терминология;
- BPMNSTORM Project;

Задача выполнена.
Результат: [диаграмма BPMN на BPMNStorm](https://storm.bpmn2.ru/#/diagram?uuid=09f6b9d0-a613-48e0-9660-c9d4e7e3b050), [терминология](https://www.trinion.org/blog/kratkoe-opisanie-bpmn-s-primerom).

**Comment by KolovMaksim** [comment]
Задача выполнена.
Результат: [диаграмма BPMN на BPMNStorm](https://storm.bpmn2.ru/#/diagram?uuid=09f6b9d0-a613-48e0-9660-c9d4e7e3b050).
