### ISSUE TITLE
SWOT: SWOT-терминология

### ISSUE THREAD

**Issue by VittoTory** [stankin/oop-model#27]
Изучение SWOT-терминологии и создание краткого глоссария для остальных участников команды.

Задание выполнено.
Результат: [doc](https://github.com/KolovMaksim/KolovMaksim.github.io/blob/master/%D0%90%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BC%D0%B5%D1%82%D0%BD%D0%BE%D0%B9%20%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D0%B8%20SWOT.doc).

**Comment by KolovMaksim** [comment]
Задание выполнено.

Результат: [doc](https://github.com/KolovMaksim/KolovMaksim.github.io/blob/master/%D0%90%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BC%D0%B5%D1%82%D0%BD%D0%BE%D0%B9%20%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D0%B8%20SWOT.doc).
