### ISSUE TITLE
SWOT: существующие реализации

### ISSUE THREAD

**Issue by VittoTory** [stankin/oop-model#29]
Поиск и краткое описание аналогов ПП, выделение основных функций и преимуществ.

Результат: [документ](https://github.com/ndkator/ndkator.github.io/blob/master/doc/%D0%A1%D1%83%D1%89%D0%B5%D1%81%D1%82%D0%B2%D1%83%D1%8E%D1%89%D0%B8%D0%B5%20%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8.docx).

**Comment by ndkator** [comment]
Работа выполнена.
Результат: [документ](https://github.com/ndkator/ndkator.github.io/blob/master/doc/%D0%A1%D1%83%D1%89%D0%B5%D1%81%D1%82%D0%B2%D1%83%D1%8E%D1%89%D0%B8%D0%B5%20%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8.docx).
