### ISSUE TITLE
SWOT: выделение функций, которые будут реализованы

### ISSUE THREAD

**Issue by VittoTory** [stankin/oop-model#30]
Описание основного функционала.

Задача выполнена.
Результат: [doc](https://github.com/ndkator/ndkator.github.io/blob/master/doc/%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%20%D0%BA%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%83.docx).

**Comment by VittoTory** [comment]
Результаты работы:

**Comment by ndkator** [comment]
Задача выполнена.
Результат: [doc](https://github.com/ndkator/ndkator.github.io/blob/master/doc/%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%20%D0%BA%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%83.docx).
