### ISSUE TITLE
UML Class Diagram

### ISSUE THREAD

**Issue by AlexeyKoreshkov** [stankin/oop-model#43]
**Как:** РП
**Хочу:** видеть формализованные данные для преобразования к UML Class Diagram
**Чтобы:** в дальнейшем можно было осуществить данное преобразование
**Приемочный тест:** в качестве приемочного теста необходимо увидеть преобразования исходных данных пользователя в UML Class Diagram в экранной форме

**Comment by proff1337q** [comment]
**Как**: ПП
**Хочу:** Получить спроектированные структуры данных и макет интерфейса от архитектора
**Чтобы**: Разработать и реализовать программный модуль для преобразования данных в UML Class Diagram
**Приемочный тест**: Структуры данных в виде текстового файла и макет интерфейса в виде изображения

**Comment by victoriapdmr** [comment]
**Как:** БА
**Хочу:**Получить готовый продукт
**Чтобы:**Провести тестирование программного продукта
**Приемочный тест:**Подбор тестовых данных и их тестирование на продукте

**Comment by serapunga** [comment]
**Как:** НИ
**Хочу:** Получить проанализированные данные
**Чтобы:** Спроектировать модуль преобразования данных и макет интерфейса
**Приемочный тест:** Проанализированные данные в виде текста
